//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMesSystemClassLibrary.ExternalComponents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewManagementDBTablesEntities : DbContext
    {
        public NewManagementDBTablesEntities()
            : base("name=NewManagementDBTablesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
    }
}
