//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMesSystemClassLibrary.ExternalComponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public string OrderNumber { get; set; }
        public string CatalogID { get; set; }
        public string MachineName { get; set; }
        public string AmountToProduce { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public string CreatorID { get; set; }
        public string LanguageCode { get; set; }
    }
}
